sudo: 
  required
  # false

language: 
  c 

services:
  - docker

# addons:
#  apt:
#    packages:
#    - gfortran

env:
  NNODES=3

before_install:
  # # update Docker
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-engine wget
  - wget https://github.com/docker/compose/releases/download/1.7.1/docker-compose-`uname -s`-`uname -m`
  - sudo mv docker-compose-`uname -s`-`uname -m` /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose

script:
  - pwd
  - docker-compose --version

  # - make NNODES=${NNODES} cluster_provision
  - docker-compose scale master=1 node="${NNODES}"

  - docker-compose exec --privileged master /update-petsc-hs.sh
  
  - docker-compose exec --privileged master mpirun -n ${NNODES} stack exec petsc-example
  
  # - make cluster_shutdown
  - docker-compose down
  
  # # # check network env
  # - cat /etc/hosts
  # - ifconfig
  
  # - docker-compose up &> logfile &
  # - sleep 60
  # - docker network ls
  # # # shut down docker-compose
  # - docker-compose down
  # - cat logfile