



# compute-master:
#     image: ocramz/compute-master-node
#     environment:
#      - RUN_SERVER='true'
#      - BOOTSTRAP_CONSUL='true'
#     ports:
#      - "8500:8500"
#     container_name: compute-master
#     hostname: compute-master
#     dns: 127.0.0.1
#     privileged: true
#     entrypoint: bin/run-consul.sh

# compute-ca:
#     image: ocramz/compute-ca
#     environment:
#      # - RUN_SERVER='true'
#      # - BOOTSTRAP_CONSUL='true'
#     ports:
#      - "8500:8500"
#     container_name: compute-ca
#     hostname: compute-ca
#     dns: 127.0.0.1
#     privileged: true
#     entrypoint: bin/run-consul.sh