master:
  # image: ocramz/compute-master-node
  build: ./petsc-hs/docker/master/Dockerfile
  ports:
    - "22"
  links:
    - node

node:
  # image: ocramz/compute-node
  build: ./petsc-hs/docker/node/Dockerfile  