compute-master:
    image: ocramz/compute-master-node
    environment:
     - RUN_SERVER=true
     - BOOTSTRAP_CONSUL=true
    ports:
     - "8500:8500"
    container_name: compute-master
    hostname: compute-master
    dns: 127.0.0.1
    privileged: true